[features]
seeds = false
[programs.localnet]
buymesomesol = "4Z7X9qTqm2yzodfFiToCKxpto6bASMV7q119SjdBQ7cu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/quinlanalexander/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
